version: '3.7'
services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "%s"
    ports:
      - "5432:5432"
    healthcheck:
      test: [“CMD-SHELL”, “pg_isready”]
      interval: 1s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  main_app:
    container_name: server
    image: "%s"
    depends_on:
      db:
        condition: service-healthy
    ports:
      - "80:8000"
    restart: always