name: build image
on:
    workflow_dispatch:

    workflow_call:
      inputs:
        COMMIT_SHA:
          description: Commit SHA for image tag
          required: true
          type: string
      
      secrets:
        DOCKERHUB_USERNAME:
          description: Dockerhub username
          required: true
        DOCKERHUB_TOKEN:
          description: Dockerhub token
          required: true
      
      outputs:
        IMAGE_TAG:
          description: Image tag to use in compose
          value: 

    release:
        types: [published]

env:
    COMMIT_SHA: ${{ github.sha }}
    USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    
    
jobs:
    build:
      runs-on: ubuntu-latest
      outputs:
        image_tag: ${{ steps.push.outputs.image_tag }}
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        
        - name: Build and push
          uses: docker/build-push-action@v4
          id: push
          with:
            context: ./sample-server
            push: true
            tags: ${{ env.USERNAME }}/sampleserver:${{ env.COMMIT_SHA }}
          
        - run: echo "${{ steps.push.outputs.imageid }}""

        - id: echo  
          run: echo "image_tag=${{ env.USERNAME }}/sampleserver:${{ env.COMMIT_SHA }}" >> $GITHUB_OUTPUT


