name: setup duckdns
on:
    workflow_dispatch:

    workflow_call:
      inputs:
        EXTERNAL_IP:
          description: VM external ip
          required: true
          type: string  

        DOMAIN:
          description: DuckDNS domain
          required: true
          type: string

      secrets:
        DUCKDNS_TOKEN:
          description: DuckDNS token
          required: true

      outputs:
        RESULT:
          description: Result
          value: ${{ jobs.setup.outputs.result }}

env:
    TOKEN: ${{ secrets.DUCKDNS_TOKEN }}
    
    
jobs:
    setup:
      runs-on: ubuntu-latest
      outputs:
        result: ${{ steps.request.outputs.result }}
      steps:
        - id: request
          run: echo 'result=$(echo url="https://www.duckdns.org/update?domains=${{ inputs.DOMAIN }}&token=${{ env.TOKEN }}&ip=${{ inputs.EXTERNAL_IP }}" | curl -k -K -)' >> $GITHUB_OUTPUT


