name: setup duckdns
on:
    workflow_dispatch:

    workflow_call:
      inputs:
        EXTERNAL_IP:
          description: VM external ip
          required: true
          type: string  

        DOMAIN:
          description: DuckDNS domain
          required: true
          type: string

      secrets:
        DUCKDNS_TOKEN:
          description: DuckDNS token
          required: true

      outputs:
        RESULT:
          description: Result
          value: ${{ jobs.setup.outputs.result }}
      
jobs:
    setup:
      runs-on: ubuntu-latest
      outputs:
        result: ${{ steps.request.outputs.result }}
      env:
        TOKEN: ${{ secrets.DUCKDNS_TOKEN }}
        DOMAIN: ${{ inputs.DOMAIN }}
        IP: ${{ inputs.EXTERNAL_IP }}
      steps:
        - id: request
          run: curl --url "https://www.duckdns.org/update?domains=${{ env.DOMAIN }}&token=${{ env.TOKEN }}&ip=${{ env.IP }}"