name: deploy
on:
  workflow_dispatch:

jobs:
  build-image:
    uses: ./.github/workflows/build_image.yml
    with:
      COMMIT_SHA: ${{ github.sha }}
      DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
      IMAGE_NAME: ${{ vars.IMAGE_NAME }}
      BUILD_CONTEXT: ${{ vars.BUILD_CONTEXT }}
    secrets: inherit

  apply-terraform:
    uses: ./.github/workflows/terraform_deploy.yml
    needs: build-image
    with:
      image_tag: ${{ needs.build-image.outputs.IMAGE_TAG }}
    secrets: inherit

  setup-duckdns:
    uses: ./.github/workflows/duckdns-setup.yml
    needs: apply-terraform
    with:
      EXTERNAL_IP: ${{ needs.apply-terraform.outputs.VM_EXTERNAL_IP }}
      DOMAIN: sus-magic
    secrets: inherit
