name: terraform apply
on: 
  release:
    types: [published]
  
  workflow_dispatch:

  workflow_call:
    inputs:
      image_tag:
        description: image tag
        required: true
        type: string
    
    secrets:
      TF_VAR_CLOUD_ID:
        required: true

      TF_VAR_FOLDER_ID:
        required: true

      TF_VAR_SUBNET_ID:
        required: true

      TF_VAR_LOGGING_GROUP_ID:
        required: true

      TF_VAR_SA_KEY:
        required: true
        
      TF_VAR_SSH_KEY:
        required: true
    
    outputs:
      VM_EXTERNAL_IP:
        description: VM external ip
        value: ${{ jobs.apply-terraform.outputs.external_ip }}

defaults:
  run:
    working-directory: ./terraform

env:
  TF_VAR_cloud_id: ${{ secrets.TF_VAR_CLOUD_ID }}
  TF_VAR_folder_id: ${{ secrets.TF_VAR_FOLDER_ID }}
  TF_VAR_subnet_id: ${{ secrets.TF_VAR_SUBNET_ID }}
  TF_VAR_logging_group_id: ${{ secrets.TF_VAR_LOGGING_GROUP_ID }}
  TF_VAR_sa_key: ${{ secrets.TF_VAR_SA_KEY }}
  TF_VAR_ssh_key: ${{ secrets.TF_VAR_SSH_KEY }}
  TF_VAR_image_tag: ${{ inputs.image_tag }}
  TF_VAR_postgres_password: ${{ secrets.TF_VAR_POSTGRES_PASSWORD }}

jobs:
  apply-terraform:
    runs-on: ubuntu-latest
    outputs:
      external_ip: ${{ steps.ext.outputs.stdout }}
    steps:
      - uses: actions/checkout@v3
      
      - uses: hashicorp/setup-terraform@v2

      - run: echo "${{ inputs.image_tag }}"

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
      
      - name: terraform init
        id: init  
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate
      
      - name: terraform plan
        id: plan
        run: terraform plan

      - name: terraform apply
        id: apply
        run: terraform apply -auto-approve
      
      - name: extract external ip
        id: ext
        run: terraform output -raw external_ip

      

